### ISSUE TITLE
URL parsing in PM

### ISSUE THREAD

**Issue by derchrisuk** [webSPELL/webSPELL#160]
internal URLs, without `http://`, sent in a PM, are no longer parsed using BBCode.
Only links sent which includes `http://` are parsed and shown as an `a href` link.

**Comment by Phhere** [comment]
Should be fixed with ae6840e8fb079928c3b3840506aecdb70f76f027

**Comment by derchrisuk** [comment]
I just tested, and is still the same.
Links in PM get only parsed if they are prefixed with HTTP.
Regardless if I use URL bbcode or just plain link

**Comment by Phhere** [comment]
I think that urls in plain text should just be detected if they start with http:// https:// or www.
Everything else needs to be put into [url] tags

**Comment by derchrisuk** [comment]
I agree for normal, not bbcode elements.
But as this is bbcode related, anything between the url tags should be treated as such.
At the moment only http[s] links are converted.
And www should be removed, as it is just a subdomain.
So a generic Url check for bbcode would only verify <name>.<tld>.
How this can be done is another story.

**Comment by Phhere** [comment]
Some update with cde583f3af67fc4c2098535fdf5aa8097b2a81cc

**Comment by Phhere** [comment]
Damn . totally broken :D

**Comment by Phhere** [comment]
Update with 8c9f5e9a2b860f57c10a9fd1749e52c040e0b8d3
